### ISSUE TITLE
Firefox issue- cannot open a websocket connection to a Jawampa Router

### ISSUE THREAD

**Issue by datsat** [Matthias247/jawampa#19]
Hi,
Thank you very much for your project. It is very helpful to my work. I have a problem. Could you please help me?

Router: I open a jawampa websocket router.
Client:
case 1: I open a jawampa websocket client. Pub/Sub, Call Procedure work perfectly.
case 2: I create a HTML page with Javascipt code to open a websocket client.
          - 2a. Pub/Sub, Call Procedure work perfectly with Chrome and Opera
          - 2b. Firefox has problem. It cannot open a connection (So Pub/Sub, Call Procedure of course do not work)

QUESTION: Why if I open the HTML page in Firefox, it cannot open a connection?
ANSWER:
In browser debug mode, I see that Chrome & Opera send "ws://uri" request
GET ws://localhost:8980/websocketdemo HTTP/1.1
Host: localhost:8980
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: null
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Sec-WebSocket-Key: FvZnlLuQeKMH+k8XMiDQMg==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Protocol: wamp.2.json

Meanwhile, Firefox sends "http://uri" request. As a consequence, in the server, we go to the method ws.wamp.jawampa.transport.SimpleWampWebsocketListener.WebSocketServerHandler.handleHttpRequest(ChannelHandlerContext ctx, FullHttpRequest req) (In the SimpleWampWebsocketListener.java file) to process this http request. Therefore, there is no handshake and no connection.

I can fix the problem by tricky work. In the method handleHttpRequest above, I call method tryWebsocketHandshake (of course, I change tryWebsocketHandshake  from private to public) from the WampServerWebsocketHandler object that you add to the pipeline (pipeline.addLast(new WampServerWebsocketHandler(uri.getPath(), router))). But this is tricky and not good. By the way, I do not really understand websocket, just know how to use it.

SO, COULD YOU PLEASE UPGRADE YOUR CODE so that it can also work with Firefox???

**Comment by Matthias247** [comment]
I'm guessing you encountered the same issue that was described and fixed here: https://github.com/Matthias247/jawampa/pull/16

If it's true then it should now be fixed in the master tree. Just let me see through some other topics - then I will also publish a new release version.

**Comment by datsat** [comment]
Thank you very much for the new code. It works now with Firefox.
