### ISSUE TITLE
  content-based publish/subscribe middleware

### ISSUE THREAD

**Issue by dhaowoods** [Matthias247/jawampa#26]
Is wamp fall into category of topic-based publish-subscribe middleware? how is different from content-based publish/subscribe middleware like [padres](http://msrg.utoronto.ca/projects/padres/index.php) and [IBM Gryphon](http://www.research.ibm.com/distributedmessaging/gryphon.html) ?

**Comment by Matthias247** [comment]
Hi!

As this is really a more general WAMP related question than about this library and you have already openend a discussion on the mailing list about this topic (https://groups.google.com/forum/#!topic/wampws/6ckczGwjFQ8) I will close this issue here.
