### ISSUE TITLE
wss secure websocket connection support 

### ISSUE THREAD

**Issue by vach** [Matthias247/jawampa#27]
Does this lib support wss? I didnt find any mention of it...

**Comment by Matthias247** [comment]
As you already might have found out it's supported through netty. For detailled configuration you need to pass a Netty  `SslContext` object to the client/server. If you don't use one a default instance (which basically ignores certificates and trusts anyone) will be used.

**Comment by vach** [comment]
Yeah, thanks, I just tried a bunch of junk libs before this, and got lazy to try figure out myself, so just wrote hoping to get fast response :)
anyway this lib works like charm, thanks for your work.
i wonder how people keep creating such crappy interfaces for those libs, its just enough to look at javascript implementations...

**Comment by ixsans** [comment]
So, does this lib support wss? how to implement it?

**Comment by uzairayub** [comment]
@Matthias247 can you please mention how do it set SslContext wss ?
@ixsans have you found it ?
