### ISSUE TITLE
msgpack or json

### ISSUE THREAD

**Issue by dmtrlbdv1** [Matthias247/jawampa#36]
I trying to understand where I have to set the type of data - msgpack or json and do not found how I can change it. Is it available or not ?

**Comment by jrogers** [comment]
By default, the router and the client support both and defaults to json. If you wish to force the client to use json or msgpack with a router connection, you can use withSerializations() on WampClientBuilder to adjust it.

**Comment by dmtrlbdv1** [comment]
Thanks, but I see it is not available in 0.2.0. Is it possible to release 0.3.0 with this functionality ?

**Comment by Matthias247** [comment]
I pushed a 0.2.1 release which contains the functionality. I guess this should help you.
