### ISSUE TITLE
Run Jawampa in Apache Tomcat 8?

### ISSUE THREAD

**Issue by NonesuchRiver** [Matthias247/jawampa#38]
Hi -
   I'm interested in supporting Autobahn JS on the client side from a Tomcat server - how big a deal would it be to rehost Jawama from Netty to Tomcat's Websockets API?  I've done some programming against Tomcat's inner APIs (e.g., a custom realm), but know essentially nothing about Netty.

Thanks!

**Comment by Matthias247** [comment]
Hi,
unfortunatly the architecture is currently quite tightly bound to Netty, so it's not directly possible to just write an adapter for another websocket provider. Of course that could be changed, but I currently don't have enough time and motivation for such a big change.
I also wrote a little bit about that issue before here: #8

**Comment by NonesuchRiver** [comment]
Hi,
   Thanks for confirming what I thought.  I see that someone else forked the project to allow a different web socket implementation (although that doesn't seem to have gotten very far or been worked on recently).
