### ISSUE TITLE
Caller Identification (CALL.Options.disclose_me | bool := true)

### ISSUE THREAD

**Issue by dmtrlbdv1** [Matthias247/jawampa#46]
I tried to find any properties for Caller Identification feature but not found. Do you have any plans to support this?

**Comment by dmtrlbdv1** [comment]
I see this functionality in fork https://github.com/ichrome/jawampa/commit/f792f320e91c8312e3c2033ba2a31930ca29f4e0

**Comment by Matthias247** [comment]
Yes, this is now merged.
