### ISSUE TITLE
maximum size for "arguments" of wampCliet.publish(token, args) ?

### ISSUE THREAD

**Issue by datsat** [Matthias247/jawampa#67]
Is there a maximum size for the arguments when publishing an event?

I use this code (java): `wampClient.publish(token, response.toString());`

`response.toString())` is a long json-string in my case. It has about 70.000 characters. I have the suspicion that the event does not get published, because when I replace `response.toString` with a short string, the event gets published as expected. 

I dont know much about the internals of Wamp and an initial debugging session into the code did not provide me with much insight. As I said above, I think that the long string is causing some problems.

Any help/feedback is welcome. If you need more information, please let me know.

**Comment by Matthias247** [comment]
Hi. There is a maximum websocket frame size configured by Netty that equals to 64kb. Messages bigger than that size won't be delivered and maybe also the connection will get dropped. Don't know exactly.

However you can overwrite that limit through the `NettyWampConnectionConfig` class, which you can provide to the `NettyWampClientConnectorProvider` class. That should resolve the issue.

**Comment by beta2k** [comment]
Thank you very much, this helped.

As you said, we had to change `static final int DEFAULT_MAX_FRAME_PAYLOAD_LENGTH = 65535;` to a higher value. we now changed it to `static final int DEFAULT_MAX_FRAME_PAYLOAD_LENGTH = 2147483648;` which equals 2^31.

so now, my event with about 70000 characters in the argument arrives successfully. the new limit seems to be, however, 16777216 bytes (2^24 bytes or ~16mb). I will not exceed this limitiation, but I am really interested on who imposes this limitation? Is there some other knob which I can turn around to still increase it?

**Comment by Matthias247** [comment]
You don't need to change the jawampa source code and the `DEFAULT_MAX_FRAME_PAYLOAD_LENGTH` variable, you can just do

    client =
    WampClientBuilder.withConnectorProvider(new NettyWampClientConnectorProvider())
                     .withConnectionConfiguration((new NettyWampConnectionConfig.Builder()).withMaxFramePayloadLength(2147483648).build())
                     ....
                     .build();

Yes, you can change `MAX_WEBSOCKET_FRAME_SIZE` according to your needs. Just be aware that if you increase those limits that if malicous clients/servers pretent to send you very large websocket frames your application will try to allocate that amount of memory which can cause memory leaks or even crashes.

**Comment by datsat** [comment]
Thank you very much for your support, everything is perfect now

**Comment by sebastianwahn** [comment]
@Matthias247 can you put this somewhere on your README.md page? I had this issue also and tried to figure out whats the problem until i stumbled now on this solved ticket. Some FAQ or known issue sections with links to the solution would be great!
