### ISSUE TITLE
Android implementation of jawampa not working

### ISSUE THREAD

**Issue by mako34** [Matthias247/jawampa#70]
Hi Matthias n team!
thanks for this work!

I need to use on Android, I have referenced this lib using gradle,

All seems to work...
Im following this java example:
https://github.com/Matthias247/jawampa_crossbar/blob/master/src/main/java/ws/wamp/jawampa/CrossbarExample.java
 
the code is importing and almost working,
but
on

WampClient.Status

I get : "Cannot resolve symbol 'Status' "

is an import missing?

please find my hello world android app [intellij] on,

https://github.com/mako34/WampDroid

this is the only bug to fix so I can have the protocol working for android, how to fix?

Thanks

**Comment by mako34** [comment]
Hey guys,

so , I have now the android project compiling and starting ok, 
please find the project at
https://github.com/mako34/WampDroid/

but now i have another error:

Session ended with error io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel

What can this problem be?

thanks

**Comment by mako34** [comment]
Hi!

ok is compiling and uploading now,

pushed changes

https://github.com/mako34/WampDroid/

now the problem is that it stays in "Connecting" state, my server is running, working with crossbar hello world, browser works and iOS app works with same ip and realm, but android app stays on WampClient.ConnectingState

I guess the connection is not happening, all my clients android included point to ws://127.0.0.1:8080/ws 

What could it be ?
thanks

**Comment by Matthias247** [comment]
127.0.0.1 is your localhost address. Do you have crossbar running on your Android device? I don't think so. If you have it running on the android emulator and want to connect to a socket on the PC you need to use 10.0.2.2, see http://developer.android.com/tools/devices/emulator.html#networkaddresses

Sorry, don't have time to review your code in detail. But jrogers already did an example for jawampa on Android: https://github.com/jrogers/AndroidWampExample

**Comment by mako34** [comment]
ohh! duhh! he he! is all working great thanks!
