### ISSUE TITLE
Request hat no Meta Information about the Caller

### ISSUE THREAD

**Issue by Kostronor** [Matthias247/jawampa#74]
As it seems, this was already done with #46 but the version containing the fix never got it to maven. Can you up the version there?

>When you (on client side) register a procedure to be remotely called, you only get a Request object per call. The Request object contains no session information and no methods to retrieve it.

>Suggestion:
>Allow for flags like `disclose_caller` when registering procedures and give this information to the Request object for retrieval.

**Comment by Kostronor** [comment]
As it seems, this was already done with #46 but the version containing the fix never got it to maven. Can you up the version there?

**Comment by Matthias247** [comment]
Setting disclose_me was merged and is available in the current maven release with `CallFlags`:
https://github.com/Matthias247/jawampa/blob/master/jawampa-core/src/main/java/ws/wamp/jawampa/CallFlags.java#L24
https://github.com/Matthias247/jawampa/blob/master/jawampa-core/src/main/java/ws/wamp/jawampa/client/SessionEstablishedState.java#L459-L462

**Comment by Kostronor** [comment]
The current maven release is 0.3.0
https://github.com/Matthias247/jawampa/tree/mvn-repo/ws/wamp/jawampa/jawampa/0.3.0

And what I needed was this function:
https://github.com/Matthias247/jawampa/blob/master/jawampa-core/src/main/java/ws/wamp/jawampa/Request.java#L63

Which is not in the build tagged 0.3.0 so I requested that the build could be updated. The Version 0.4.1 is announced and recommended on the start page 

```
<dependency>
    <groupId>ws.wamp.jawampa</groupId>
    <artifactId>jawampa-core</artifactId>
    <version>0.4.1</version>
</dependency>
```

But is not resolved as a dependency as the maven branch was not updated.

I since then found https://jitpack.io/ which builds the dependency for me, but it would be nice to have an updated maven repo.

**Comment by Matthias247** [comment]
You are on the wrong maven repo. The new versions are on maven central.

**Comment by Matthias247** [comment]
http://search.maven.org/#search|ga|1|jawampa

**Comment by Kostronor** [comment]
Alright, will look where I found the outdated information and see if the docs get edited.
