### ISSUE TITLE
Issue in load testing

### ISSUE THREAD

**Issue by dhavalstays** [Matthias247/jawampa#80]
I have application server in Java and I'm using WAMP for communication between client and server. Everything works fine, But now I want to load test this application , So I have written simple Java program, which creates unique thread for each server request. When I run this program a weird thing happens and I have no clue why it is happening this way, When I create more than 120 threads, for many threads I get statusChanged as disconnected. Am I missing something here? Below 120 threads every thread gets connected to server. Can anyone guide me?

**Comment by the20login** [comment]
Could you provide source code please? And hardware configuration, if possible.

**Comment by Matthias247** [comment]
Closing due to missing information
