### ISSUE TITLE
run in ant build

### ISSUE THREAD

**Issue by nicole800716** [Matthias247/jawampa#84]
Hello, 

As title, could it build as library jar, and  just add external jar for ant build project.
or it just can run in apache maven?
Sorry for that I'm beginner of java, so I don't know is it possible, and how to do it.

Regards,
nicole

**Comment by Matthias247** [comment]
That's more or less a question/issue around the Ant and maven build tools and not about this library. As I'm no expert there I can't answer it right away and close this. But I'm pretty sure that using Maven bundles as Ant dependencies is possible, and a short search should find the exact solution.
