### ISSUE TITLE
How to influence the json encoding/decoding? JsonViews possible?

### ISSUE THREAD

**Issue by voodinator** [Matthias247/jawampa#96]
Hi, i guess the wamp client use Jackson 2 to encode/decode the parameters to and from json? Is it possible to make use of JsonViews? I dont know where i could pass which view to use for each call. The documentation says 'for more complex data structures you might need to use annotations to instruct the serializer.' Does anyone have some examples for that or a helpful link?

**Comment by Matthias247** [comment]
You can pass a custom ObjectMapper to the WampClientBuilder in order to influence de/encoding. I don't know what JsonViews are, so I can't help you there. Regarding Jackson version: Best thing is to look it up in the dependencies of the library - don't know it out of my head :)
